/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_deer_cuda_ReachabilityFence */

#ifndef _Included_net_deer_cuda_ReachabilityFence
#define _Included_net_deer_cuda_ReachabilityFence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_deer_cuda_ReachabilityFence
 * Method:    protectN
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_net_deer_cuda_ReachabilityFence_protectN
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
