/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_deer_cuda_DeviceMemory */

#ifndef _Included_net_deer_cuda_DeviceMemory
#define _Included_net_deer_cuda_DeviceMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_deer_cuda_DeviceMemory
 * Method:    cudaMallocN
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_net_deer_cuda_DeviceMemory_cudaMallocN
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     net_deer_cuda_DeviceMemory
 * Method:    cudaFreeN
 * Signature: (Lnet/deer/cuda/Address;)J
 */
JNIEXPORT jlong JNICALL Java_net_deer_cuda_DeviceMemory_cudaFreeN
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_deer_cuda_DeviceMemory
 * Method:    cudaMemcpyHostToDeviceN
 * Signature: (Lnet/deer/cuda/Address;[FII)V
 */
JNIEXPORT void JNICALL Java_net_deer_cuda_DeviceMemory_cudaMemcpyHostToDeviceN
  (JNIEnv *, jclass, jobject, jfloatArray, jint, jint);

/*
 * Class:     net_deer_cuda_DeviceMemory
 * Method:    cudaMemcpyDeviceToHostN
 * Signature: (Lnet/deer/cuda/Address;[FII)V
 */
JNIEXPORT void JNICALL Java_net_deer_cuda_DeviceMemory_cudaMemcpyDeviceToHostN
  (JNIEnv *, jclass, jobject, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
